/* ===============================
KPI 11: customer_lifetime_value
Business Question:
-What is the lifetime value of each customer?
=============================== */

SELECT c.customer_id,
count(o.order_id) as count_orders,
sum(o.total_sales) as Revenue
from orders o
join customers c
on o.customer_id=c.customer_id
GROUP BY c.customer_id
ORDER BY Revenue DESC

/*
Insight:
This analysis calculates the total revenue generated by each customer,
which represents their customer lifetime value (CLV).

It helps businesses identify high-value customers who contribute the most to overall sales.

The results can support customer retention strategies and targeted marketing campaigns.
*/
